# Generated by Django 4.2.7 on 2024-03-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessege2',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
