# Generated by Django 4.2.7 on 2024-03-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_usermessege3_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage3',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage3',
            name='group_photo',
            field=models.ImageField(blank=True, default='users_images/vk_default.jpg', null=True, upload_to='users_images/'),
        ),
    ]
