# Generated by Django 4.2.7 on 2024-04-09 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_remove_messege_chat_room_remove_messege_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage3',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='usermessege3',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='chatmessage3',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='chatmessage3',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='chatmessage3',
            name='group_photo',
            field=models.ImageField(blank=True, default='users_images/vk_default.jpg', null=True, upload_to='users_images/', verbose_name='Изображение группы'),
        ),
        migrations.AlterField(
            model_name='chatmessage3',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='chatmessage3',
            name='user',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='usermessege3',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='chat.chatmessage3', verbose_name='Номер чата'),
        ),
        migrations.AlterField(
            model_name='usermessege3',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='usermessege3',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='usermessege3',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
