# Generated by Django 4.2.7 on 2024-03-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users_images/vk_default.jpg', null=True, upload_to='users_images/', verbose_name='photo_user'),
        ),
    ]
