# Generated by Django 4.2.7 on 2024-03-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.BooleanField(default=False, verbose_name='online_status'),
        ),
    ]
